import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
export const mediaAssets = sqliteTable(
  "media_assets",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    file_Id: text("file_Id"),
    fileName: text("fileName").notNull(),
    fileType: text("fileType", { enum: ["image", "video", "audio", "document", "other"] }).notNull().default("image"),
    mimeType: text("mimeType").notNull(),
    url: text("url").notNull(),
    thumbnailUrl: text("thumbnailUrl"),
    sizeBytes: integer("sizeBytes"),
    width: integer("width"),
    height: integer("height"),
    durationSeconds: integer("durationSeconds"),
    altText: text("altText"),
    source: text("source", { enum: ["upload", "ai_generated", "website_scrape", "platform_import"] }).notNull().default("upload"),
    tags: text("tags", { mode: "json" }).$type<string[]>().default(sql`[]`),
    metadata: text("metadata", { mode: "json" }).$type<Record<string, any>>().notNull().default(sql`'{}'`),
    workspace_id: text("workspace_id"),
    uploadedBy_id: text("uploadedBy_id"),
    account_id: text("account_id").notNull(),
    createdAt: integer("createdAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: integer("updatedAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
    deletedAt: integer("deletedAt", { mode: "timestamp" }),
  },
);

export const posts = sqliteTable(
  "posts",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    title: text("title").notNull(),
    headline: text("headline"),
    body: text("body"),
    description: text("description"),
    postType: text("postType", { enum: ["organic", "promoted"] }).notNull().default("organic"),
    contentType: text("contentType", { enum: ["text", "image", "carousel", "video", "reel", "story", "brand_card"] }).notNull().default("image"),
    status: text("status", { enum: ["draft", "in_review", "scheduled", "publishing", "published", "failed", "archived"] }).notNull().default("draft"),
    format: text("format"),
    scheduledAt: integer("scheduledAt", { mode: "timestamp" }),
    publishedAt: integer("publishedAt", { mode: "timestamp" }),
    callToAction: text("callToAction"),
    destinationUrl: text("destinationUrl"),
    fieldValues: text("fieldValues", { mode: "json" }).$type<Record<string, any>>().notNull().default(sql`'{}'`),
    schedulingMetadata: text("schedulingMetadata", { mode: "json" }).$type<Record<string, any>>().notNull().default(sql`'{}'`),
    imagePrompt: text("imagePrompt"),
    metrics: text("metrics", { mode: "json" }).$type<Record<string, any>>().notNull().default(sql`'{}'`),
    notes: text("notes"),
    workspace_id: text("workspace_id"),
    createdBy_id: text("createdBy_id"),
    account_id: text("account_id").notNull(),
    createdAt: integer("createdAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: integer("updatedAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
    deletedAt: integer("deletedAt", { mode: "timestamp" }),
  },
);

export const creatives = sqliteTable(
  "creatives",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    headline: text("headline"),
    body: text("body"),
    shotType: text("shotType"),
    subject: text("subject"),
    aspectRatios: text("aspectRatios", { mode: "json" }).$type<string[]>().default(sql`[]`),
    placements: text("placements", { mode: "json" }).$type<string[]>().default(sql`[]`),
    status: text("status", { enum: ["generating", "pending", "approved", "rejected", "redo_requested", "archived"] }).notNull().default("pending"),
    rejectReason: text("rejectReason", { enum: ["wrong_tone", "wrong_product", "bad_image", "off_brand", "other"] }),
    rejectNote: text("rejectNote"),
    isAiGenerated: integer("isAiGenerated", { mode: "boolean" }).notNull().default(true),
    prompt: text("prompt"),
    brandContext: text("brandContext", { mode: "json" }).$type<Record<string, any>>().notNull().default(sql`'{}'`),
    generationMeta: text("generationMeta", { mode: "json" }).$type<Record<string, any>>().notNull().default(sql`'{}'`),
    generatedAt: integer("generatedAt", { mode: "timestamp" }),
    reviewedAt: integer("reviewedAt", { mode: "timestamp" }),
    workspace_id: text("workspace_id"),
    campaign_id: text("campaign_id"),
    mediaAsset_id: text("mediaAsset_id"),
    reviewedBy_id: text("reviewedBy_id"),
    account_id: text("account_id").notNull(),
    createdAt: integer("createdAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: integer("updatedAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
    deletedAt: integer("deletedAt", { mode: "timestamp" }),
  },
);

export const campaignPosts = sqliteTable(
  "campaign_posts",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    platformPostId: text("platformPostId"),
    platformAdId: text("platformAdId"),
    targeting: text("targeting", { mode: "json" }).$type<Record<string, any>>().notNull().default(sql`'{}'`),
    platformCreative: text("platformCreative", { mode: "json" }).$type<Record<string, any>>().notNull().default(sql`'{}'`),
    metrics: text("metrics", { mode: "json" }).$type<Record<string, any>>().notNull().default(sql`'{}'`),
    reviewStatus: text("reviewStatus", { enum: ["pending", "approved", "rejected", "not_required"] }).notNull().default("pending"),
    reviewFeedback: text("reviewFeedback"),
    startedAt: integer("startedAt", { mode: "timestamp" }),
    endedAt: integer("endedAt", { mode: "timestamp" }),
    campaign_id: text("campaign_id"),
    post_id: text("post_id"),
    platform_id: text("platform_id"),
    connection_id: text("connection_id"),
    account_id: text("account_id").notNull(),
    createdAt: integer("createdAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: integer("updatedAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => [
    uniqueIndex("campaign_posts_campaign_id_post_id_platform_id_ux").on(t.campaign_id, t.post_id, t.platform_id),
  ],
);

export const scheduledPosts = sqliteTable(
  "scheduled_posts",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    scheduledAt: integer("scheduledAt", { mode: "timestamp" }).notNull(),
    status: text("status", { enum: ["queued", "publishing", "published", "failed", "cancelled"] }).notNull().default("queued"),
    priority: text("priority", { enum: ["low", "normal", "high"] }).notNull().default("normal"),
    publishedAt: integer("publishedAt", { mode: "timestamp" }),
    attempts: integer("attempts").notNull().default(0),
    lastAttemptAt: integer("lastAttemptAt", { mode: "timestamp" }),
    nextRetryAt: integer("nextRetryAt", { mode: "timestamp" }),
    jobId: text("jobId"),
    errorMessage: text("errorMessage"),
    lastError: text("lastError", { mode: "json" }).$type<Record<string, any>>().default(sql`'{}'`),
    externalPostId: text("externalPostId"),
    workspace_id: text("workspace_id"),
    post_id: text("post_id"),
    platform_id: text("platform_id"),
    connection_id: text("connection_id"),
    account_id: text("account_id").notNull(),
    createdAt: integer("createdAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: integer("updatedAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
  },
);

export const campaignAnalytics = sqliteTable(
  "campaign_analytics",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    date: integer("date", { mode: "timestamp" }).notNull(),
    hour: integer("hour"),
    impressions: integer("impressions").notNull().default(0),
    clicks: integer("clicks").notNull().default(0),
    conversions: integer("conversions").notNull().default(0),
    storeVisits: integer("storeVisits").notNull().default(0),
    spend: real("spend").notNull().default(0),
    revenue: real("revenue").notNull().default(0),
    ctr: real("ctr"),
    cpc: real("cpc"),
    cpa: real("cpa"),
    roas: real("roas"),
    frequency: real("frequency"),
    deviceBreakdown: text("deviceBreakdown", { mode: "json" }).$type<Record<string, any>>().notNull().default(sql`'{}'`),
    metrics: text("metrics", { mode: "json" }).$type<Record<string, any>>().notNull().default(sql`'{}'`),
    workspace_id: text("workspace_id"),
    campaign_id: text("campaign_id"),
    platform_id: text("platform_id"),
    account_id: text("account_id").notNull(),
    createdAt: integer("createdAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: integer("updatedAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => [
    uniqueIndex("campaign_analytics_campaign_id_platform_id_date_hour_ux").on(t.campaign_id, t.platform_id, t.date, t.hour),
  ],
);

export const campaignLandingPages = sqliteTable(
  "campaign_landing_pages",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    slug: text("slug").notNull(),
    status: text("status", { enum: ["draft", "generating", "ready", "published", "failed", "archived"] }).notNull().default("draft"),
    version: integer("version").notNull().default(1),
    content: text("content", { mode: "json" }).$type<Record<string, any>>().notNull().default(sql`'{}'`),
    theme: text("theme", { mode: "json" }).$type<Record<string, any>>().notNull().default(sql`'{}'`),
    ctaDestinationUrl: text("ctaDestinationUrl"),
    error: text("error"),
    publishedAt: integer("publishedAt", { mode: "timestamp" }),
    workspace_id: text("workspace_id"),
    campaign_id: text("campaign_id"),
    account_id: text("account_id").notNull(),
    createdAt: integer("createdAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: integer("updatedAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => [
    uniqueIndex("campaign_landing_pages_slug_ux").on(t.slug),
  ],
);

export const websiteScrapedAssets = sqliteTable(
  "website_scraped_assets",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    workspace_id: text("workspace_id"),
    url: text("url").notNull(),
    title: text("title"),
    metaDescription: text("metaDescription"),
    metaKeywords: text("metaKeywords", { mode: "json" }).$type<string[]>().default(sql`[]`),
    headings: text("headings", { mode: "json" }).$type<any[]>().notNull().default(sql`[]`),
    bodyText: text("bodyText"),
    ctaButtons: text("ctaButtons", { mode: "json" }).$type<string[]>().default(sql`[]`),
    images: text("images", { mode: "json" }).$type<any[]>().notNull().default(sql`[]`),
    brandColors: text("brandColors", { mode: "json" }).$type<string[]>().default(sql`[]`),
    brandName: text("brandName"),
    fonts: text("fonts", { mode: "json" }).$type<string[]>().default(sql`[]`),
    extractedAt: integer("extractedAt", { mode: "timestamp" }),
    draft_id: text("draft_id"),
    createdAt: integer("createdAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: integer("updatedAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
  },
);

export const postFields = sqliteTable(
  "post_fields",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    name: text("name").notNull().unique(),
    label: text("label").notNull(),
    fieldType: text("fieldType", { enum: ["text", "textarea", "url", "select", "multiselect", "number", "boolean", "media", "date"] }).notNull().default("text"),
    scope: text("scope", { enum: ["post", "campaign", "both"] }).notNull().default("post"),
    defaultValidation: text("defaultValidation", { mode: "json" }).$type<Record<string, any>>().notNull().default(sql`'{}'`),
    options: text("options", { mode: "json" }).$type<any[]>().notNull().default(sql`[]`),
    description: text("description"),
    displayOrder: integer("displayOrder").notNull().default(0),
    isActive: integer("isActive", { mode: "boolean" }).notNull().default(true),
    createdAt: integer("createdAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: integer("updatedAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => [
    uniqueIndex("post_fields_name_ux").on(t.name),
  ],
);

export const platformPostFields = sqliteTable(
  "platform_post_fields",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    isRequired: integer("isRequired", { mode: "boolean" }).notNull().default(false),
    labelOverride: text("labelOverride"),
    placeholder: text("placeholder"),
    helpText: text("helpText"),
    validationOverride: text("validationOverride", { mode: "json" }).$type<Record<string, any>>().default(sql`'{}'`),
    optionsOverride: text("optionsOverride", { mode: "json" }).$type<any[]>().default(sql`[]`),
    displayOrder: integer("displayOrder").notNull().default(0),
    isActive: integer("isActive", { mode: "boolean" }).notNull().default(true),
    platform_id: text("platform_id"),
    field_id: text("field_id"),
    createdAt: integer("createdAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: integer("updatedAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => [
    uniqueIndex("platform_post_fields_platform_id_field_id_ux").on(t.platform_id, t.field_id),
  ],
);

// Join table for the posts <-> media_assets M2M declared in the Baasix schema.
export const postMedia = sqliteTable(
  "post_media",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    post_id: text("post_id").notNull(),
    media_id: text("media_id").notNull(),
    createdAt: integer("createdAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: integer("updatedAt", { mode: "timestamp" }).notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => [
    uniqueIndex("post_media_post_id_media_id_ux").on(t.post_id, t.media_id),
  ],
);
