import type { SQLiteTable } from "drizzle-orm/sqlite-core";
import {
  adPlatforms,
  agencyClients,
  agencyStaffWorkspaces,
  aiSettings,
  auditLog,
  billingSettings,
  brandProfiles,
  brandScrapeDrafts,
  campaignActivities,
  campaignAnalytics,
  campaignIterations,
  campaignLandingPages,
  campaignPlatforms,
  campaignPosts,
  campaignTemplates,
  campaigns,
  clients,
  creatives,
  dashboardMetricPrefs,
  deletionRequests,
  files,
  invites,
  mediaAssets,
  notificationPreferences,
  notifications,
  platformConfigs,
  platformConnections,
  platformPostFields,
  postFields,
  posts,
  scheduledPosts,
  subscriptionPlans,
  subscriptions,
  tenants,
  usageCounters,
  userProfiles,
  users,
  userTokens,
  websiteScrapedAssets,
  workspaceMembers,
  workspaceSettings,
  workspaces,
} from "./schema/index.js";

// Maps every collection name (SQL table name) to its Drizzle table object.
export const registry: Record<string, SQLiteTable> = {
  workspaces,
  workspace_members: workspaceMembers,
  agency_clients: agencyClients,
  agency_staff_workspaces: agencyStaffWorkspaces,
  clients,
  brand_profiles: brandProfiles,
  brand_scrape_drafts: brandScrapeDrafts,
  ad_platforms: adPlatforms,
  platform_configs: platformConfigs,
  platform_connections: platformConnections,
  campaigns,
  campaign_platforms: campaignPlatforms,
  campaign_iterations: campaignIterations,
  campaign_activities: campaignActivities,
  campaign_templates: campaignTemplates,
  media_assets: mediaAssets,
  posts,
  creatives,
  campaign_posts: campaignPosts,
  scheduled_posts: scheduledPosts,
  campaign_analytics: campaignAnalytics,
  campaign_landing_pages: campaignLandingPages,
  website_scraped_assets: websiteScrapedAssets,
  post_fields: postFields,
  platform_post_fields: platformPostFields,
  user_profiles: userProfiles,
  notification_preferences: notificationPreferences,
  subscription_plans: subscriptionPlans,
  subscriptions,
  usage_counters: usageCounters,
  workspace_settings: workspaceSettings,
  dashboard_metric_prefs: dashboardMetricPrefs,
  deletion_requests: deletionRequests,
  billing_settings: billingSettings,
  ai_settings: aiSettings,
  users,
  user_tokens: userTokens,
  tenants,
  invites,
  notifications,
  audit_log: auditLog,
  files,
};

export const collectionNames: string[] = Object.keys(registry);
